# Generated by Django 4.2.20 on 2025-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('motivational_letter', models.TextField(blank=True, null=True)),
                ('applying_date', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='resumes')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='was_published',
            field=models.DateField(auto_now_add=True),
        ),
    ]
